name: Request Unity Activation File

on:
  workflow_dispatch:

jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: requestActivationFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 6000.1.14f1
      - uses: actions/upload-artifact@v4
        with:
          name: unity-activation-file
          path: ${{ steps.requestActivationFile.outputs.filePath }}
